spring:
  config:
    import:
      - classpath:application-oauth.yml
      - classpath:application-aws.yml
      - classpath:application-actuator.yml
  datasource:
    url: jdbc:h2:tcp://localhost/~/dealight # (본인 DB URL)
    username: sa
    password:
    driver-class-name: org.h2.Driver #(본인 DB종류에 맞춰서)
  h2:
    console:
      enabled: true

  jpa: # depth 주의
    open-in-view: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true # 필수
  sql: # depth 주의 jpa와 같은 depth
    init:
      data-locations: classpath:data.sql
      mode: always
      platform: h2 # 본인 DB 종류
  redis:
    host: localhost
    port: 6379


logging.level:
  org.hibernate.SQL: debug
